"""third Migration

Revision ID: 069c81988646
Revises: 0f0b79440335
Create Date: 2019-09-27 16:34:12.635378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069c81988646'
down_revision = '0f0b79440335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('pitch', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'content')
    # ### end Alembic commands ###
