"""fifth Migration

Revision ID: 2f9204437b9f
Revises: 4fd7652d70d8
Create Date: 2019-09-28 12:04:40.324850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9204437b9f'
down_revision = '4fd7652d70d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch', 'description')
    # ### end Alembic commands ###
