"""Initial Migration

Revision ID: d419f58d3f89
Revises: 28a103d201ee
Create Date: 2019-09-20 20:45:48.075052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd419f58d3f89'
down_revision = '28a103d201ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_userid_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'users', ['user_id'], ['id'])
    op.drop_column('pitch', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_userid_fkey', 'pitch', 'users', ['userid'], ['id'])
    op.drop_column('pitch', 'user_id')
    # ### end Alembic commands ###
